import cv2
import numpy as np
import math
import matplotlib.pyplot as plt

def get_homography(angle_deg, w, h, distance_cm=100.0, f=1000.0):
    src_pts = np.float32([[0, 0], [w, 0], [0, h], [w, h]])
    
    theta = math.radians(angle_deg)
    half_size = 20.0 
    
    Z_left = distance_cm + half_size * math.sin(theta)
    Z_right = distance_cm - half_size * math.sin(theta)
    X_left = -half_size * math.cos(theta)
    X_right = half_size * math.cos(theta)
    Y_top = -half_size
    Y_bottom = half_size
    
    x_tl = (f * X_left) / Z_left
    y_tl = (f * Y_top) / Z_left
    x_bl = (f * X_left) / Z_left
    y_bl = (f * Y_bottom) / Z_left
    
    x_tr = (f * X_right) / Z_right
    y_tr = (f * Y_top) / Z_right
    x_br = (f * X_right) / Z_right
    y_br = (f * Y_bottom) / Z_right
    
    dst_pts = np.float32([
        [x_tl + w/2, y_tl + h/2],
        [x_tr + w/2, y_tr + h/2],
        [x_bl + w/2, y_bl + h/2],
        [x_br + w/2, y_br + h/2]
    ])
    
    H = cv2.getPerspectiveTransform(src_pts, dst_pts)
    return H

def inverse_orbital_servoing(input_image_path):
    img_c = cv2.imread(input_image_path)
    if img_c is None:
        raise ValueError(f"Could not load {input_image_path}. Did you run part_c.py?")
        
    h, w = img_c.shape[:2]
    
    # 1. Calculate the Inverse Matrix of the starting state (22.5 degrees)
    H_22_5 = get_homography(22.5, w, h)
    H_inv = np.linalg.inv(H_22_5)
    
    # 2. Define incremental camera steps back to 0 degrees
    angles = [18.0, 13.5, 9.0, 4.5, 0.0]
    
    plt.figure(figsize=(18, 5))
    plt.subplot(1, 6, 1)
    plt.imshow(cv2.cvtColor(img_c, cv2.COLOR_BGR2RGB))
    plt.title("Start (22.5°)")
    plt.axis('off')
    
    for i, theta in enumerate(angles):
        # 3. Calculate Homography for the target incremental angle
        H_theta = get_homography(theta, w, h)
        
        # 4. Multiply them to create a transformation matrix that directly 
        # maps the 22.5 degree image to the new theta degree image
        M = np.dot(H_theta, H_inv)
        
        # 5. Apply the incremental camera move
        step_img = cv2.warpPerspective(img_c, M, (w, h), borderValue=(255,255,255))
        
        plt.subplot(1, 6, i+2)
        plt.imshow(cv2.cvtColor(step_img, cv2.COLOR_BGR2RGB))
        plt.title(f"Step {i+1}: {theta}°")
        plt.axis('off')
        
    plt.tight_layout()
    plt.savefig("part_d_servoing.png")
    print("Sequence saved to part_d_servoing.png")

if __name__ == "__main__":
    # Strictly using the output generated by Part C
    inverse_orbital_servoing("synthetic_perspective.png")
